project_id = "jwvkvyhwhpbyruattzbx"

[functions.initialize-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.create-users-batch]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
