project_id = "jwvkvyhwhpbyruattzbx"

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.ensure-admins]
verify_jwt = true
