project_id = "jwvkvyhwhpbyruattzbx"

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.generate-sales-pitch]
verify_jwt = false

[functions.send-password-reset-request]
verify_jwt = false
